\documentclass{article}
\title{Vignette for package COSA}
\author{Maarten Kampert}

\begin{document}
\SweaveOpts{concordance=TRUE}

% \VignetteIndexEntry{Vignette Package for COSA}
% \VignetteDepends{base}
% \VignetteKeyword{COSA}

\maketitle



An example on how to run COSA
<<>>=
require(COSA)
#Xmat <- as.matrix(iris[,1:4])
#d <- cosa(X = Xmat)                                                           
#print(d)
@
\end{document}


